#! /usr/bin/env python
"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

MAX_NUM = 4000000

def evenfib(limit):
    """ Create an even fibonacci number generator based on the original """
    fibs = fib(limit)
    cur = next( fibs )

    while cur < limit:
        yield cur

        # Get the starting next even fib
        # This is a do while loop in python
        while True:
            cur = next( fibs )
            if (cur % 2) == 0:
                break

def fib(limit):
    """ Create a fibonacci generator """
    a, b = 0, 1
    while a <= limit:
        yield a
        a, b = b, a + b


def main():
    sum = 0
    for x in evenfib(MAX_NUM):
        sum += x

    return sum

if __name__ == "__main__":
    print( main() )
